# Generated by Django 4.1.2 on 2022-12-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_slug_alter_topic_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
