# Generated by Django 4.1.2 on 2022-12-10 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
    ]
