# Generated by Django 4.1.2 on 2022-12-10 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Текст'),
        ),
    ]
