# Generated by Django 4.1.2 on 2022-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст'),
        ),
    ]
