# Generated by Django 3.2.16 on 2022-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='topic',
            name='more_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка подробнее'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Название (en)'),
        ),
    ]
