# Generated by Django 3.2.16 on 2022-12-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='more_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Ссылка подробнее'),
        ),
    ]
