# Generated by Django 4.1.2 on 2022-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_topic_more_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='more_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Подробнее'),
        ),
    ]
