# Generated by Django 4.1.2 on 2022-12-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_topic_file_alter_topic_more_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='file',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Название')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='attachments/None/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='attachments/None/images/', verbose_name='Изображение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.topic', verbose_name='Топик')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'db_table': 'attachments',
            },
        ),
    ]
