# Generated by Django 4.1.2 on 2022-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_topic_options_remove_topic_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='attachments/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='attachments/images/', verbose_name='Изображение'),
        ),
    ]
