# Generated by Django 4.1.2 on 2022-12-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_attachment_file_alter_attachment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'parent')},
        ),
    ]
