# Generated by Django 4.1.2 on 2023-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_comment_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лайки'),
        ),
    ]
