# Generated by Django 4.1.2 on 2023-02-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
