# Generated by Django 4.1.5 on 2023-03-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_topic_learned_by_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
                'db_table': 'gallery',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='attachments/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='attachments/images/', verbose_name='Изображение')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='main.gallery', verbose_name='Галлерея')),
            ],
            options={
                'verbose_name': 'Артифакт',
                'verbose_name_plural': 'Артифакты',
                'db_table': 'artifacts',
            },
        ),
    ]
